stack-set: assumable-roles
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
all-subaccounts: true
max-concurrent-percentage: 100
regions:
  - eu-west-1
region: eu-west-1
tags:
  ValidateAllSubAccounts: true
  ValidateRegions: eu-west-1
#vars:
#  DisabledIdentitiesServices:
#    - iam
parameters:
  AllowedRegions: eu-west-1
