stack-set: config-rules
all-accounts: false
accounts:
  - 253922918127
  - 776438119252
#all-regions: true
excluded-regions:
  - eu-north-1
  - eu-north-1
  - ap-south-1
  - eu-west-3
  - eu-west-2
  - ap-northeast-2
  - ap-northeast-1
  - sa-east-1
  - ca-central-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
main-account-parameter: true
max-concurrent-percentage: 100
organization-variables: true
region: eu-west-1
vars:
  EnabledRegions:
    - eu-west-1
  EnabledConfigRules:
    EIP_ATTACHED: AWS::EC2::EIP
    INCOMING_SSH_DISABLED: AWS::EC2::SecurityGroup
    RDS_INSTANCE_PUBLIC_ACCESS_CHECK: AWS::RDS::DBInstance
    CLOUD_TRAIL_CLOUD_WATCH_LOGS_ENABLED: AWS::CloudTrail::Trail
    VPC_FLOW_LOGS_ENABLED: AWS::EC2::VPC
    S3_BUCKET_PUBLIC_READ_PROHIBITED: ['AWS::S3::Bucket', 'AWS::S3::AccountPublicAccessBlock']
    S3_BUCKET_PUBLIC_WRITE_PROHIBITED: ['AWS::S3::Bucket', 'AWS::S3::AccountPublicAccessBlock']
capabilities:
  - CAPABILITY_IAM
tags:
  ValidateAllAccounts: true
  ValidateAllRegions: true
parameters:
  GlobalConfigRegion: eu-west-1