stack-set: guardduty-member
max-concurrent-percentage: 100
# all-subaccounts: true
accounts:
  - 776438119252
#all-regions: true
excluded-regions:
  - eu-north-1
main-account-parameter: true
region: eu-west-1
tags:
  ValidateAllSubAccounts: true
  ValidateAllRegions: true
