stack-set: guardduty-member
max-concurrent-percentage: 100
# all-subaccounts: true
accounts:
  - 776438119252
#all-regions: true
excluded-regions:
  - eu-north-1
  - eu-north-1
  - ap-south-1
  - eu-west-3
  - eu-west-2
  - eu-west-1
  - ap-northeast-2
  - ap-northeast-1
  - sa-east-1
  - ca-central-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - us-east-1
  - us-east-2
  - us-west-2
main-account-parameter: true
region: eu-west-1
tags:
  ValidateAllSubAccounts: true
  ValidateAllRegions: true
