stack-set: guardduty-member
max-concurrent-percentage: 100
all-subaccounts: true
#all-regions: true
excluded-regions:
  - eu-north-1
main-account-parameter: true
region: eu-central-1
tags:
  ValidateAllSubAccounts: true
  ValidateAllRegions: true
