stack: vpc
stack-set: vpc
vars:
  AvailabilityZones: 3
# Example Endpoints for deploying an ECS Cluster
#  GatewayEndpoints:
#    - s3
#  InterfaceEndpoints:
#    - monitoring
#    - logs
#    - ecs
#    - ecs-agent
#    - ecs-telemetry
#    - ecr.dkr
#    - ecr.api
#    - cloudformation
#    - ssm
#  AccountCIDR:
#    123456789:
#      "eu-central-1": 11.0.0.0/16
parameters:
  PrivateNatGateway: none
all-subaccounts: true
regions:
  - eu-central-1
max-concurrent-percentage: 100
tags:
  ValidateAllSubAccounts: 'true'
  ValidateRegions: eu-central-1
capabilities:
  - CAPABILITY_IAM
main-account-parameter: true
region: eu-central-1
