stack-set: auditing-configuration
capabilities:
  - CAPABILITY_IAM
all-accounts: false
accounts:
  - 253922918127
  - 776438119252
#all-regions: true
excluded-regions:
  - eu-north-1
  - eu-north-1
  - ap-south-1
  - eu-west-3
  - eu-west-2
  - ap-northeast-2
  - ap-northeast-1
  - sa-east-1
  - ca-central-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
main-account-parameter: true
max-concurrent-percentage: 100
region: eu-west-1
tags:
  ValidateAllAccounts: true
  ValidateAllRegions: true
parameters:
  GlobalConfigRegion: eu-west-1
