stack-set: auditing-configuration
capabilities:
  - CAPABILITY_IAM
all-accounts: false
#all-regions: true
excluded-regions:
  - eu-north-1
main-account-parameter: true
max-concurrent-percentage: 100
region: eu-west-1
tags:
  ValidateAllAccounts: true
  ValidateAllRegions: true
parameters:
  GlobalConfigRegion: eu-west-1
