stack: password-policy
stack-set: password-policy
all-accounts: false
max-concurrent-percentage: 100
regions:
  - eu-west-1
region: eu-west-1
capabilities:
  - CAPABILITY_IAM
tags:
  ValidateAllAccounts: true
  ValidateRegions: eu-west-1
