stack: password-policy
stack-set: password-policy
all-accounts: true
max-concurrent-percentage: 100
regions:
  - eu-central-1
region: eu-central-1
capabilities:
  - CAPABILITY_IAM
tags:
  ValidateAllAccounts: true
  ValidateRegions: eu-central-1
