stack-set: stack-set-execution-role
execution-role-name: OrganizationAccountAccessRole
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
max-concurrent-percentage: 100
# all-subaccounts: true
accounts:
  - 776438119252
regions:
  - eu-west-1
region: eu-west-1
tags:
  ValidateAllSubAccounts: true
  ValidateRegions: eu-west-1
